### PR TITLE
Docker

### PR DESCRIPTION
**Pull request by gentlecat**
- [x] Basic web app functionality
- [x] Configuration changes
- [x] Replication functionality
- [x] Mail server

### CODE REVIEW

**Comment by gentlecat** [comment]
I still can't figure out how to set up mail server for sending notification. If you have any ideas, please share.

**Comment by gentlecat** [comment]
Postfix container is now working... kind of. Gmail didn't accept any mail that was sent when I was testing.

**Comment by gentlecat** [comment]
Should we merge this?

**Comment by mayhem** [comment]
I've only had time for a cursory glance, but it looks vaguely ok. if this is needed for the move, then by all means, merge. 🖐

**Pull request merged**
