### PR TITLE
MEB-145: Improve non commercial sign-up page

### PR DESCRIPTION
**Pull request by amCap1712**
Ask non-commercial users to indicate which MeB datasets they intend to use. Datasets are stored in the newly added 'dataset' table. An admin view is provided as well to add new datasets.

image
image
image

### CODE REVIEW

**Comment by amCap1712** [comment]
We originally decided a multilevel dropdown but I don't see an out of the box Bootstrap 3 (there is one in Bootstrap 5) multilevel list component. I guess @MonkeyDo could help with CSS for the same.

**Comment by amCap1712** [comment]
The options in the screenshot are only for demo purposes. Actual options will be added to production using admin panel later.

**Comment by MonkeyDo** [comment]
> We originally decided a multilevel dropdown but I don't see an out of the box Bootstrap 3 (there is one in Bootstrap 5) multilevel list component. I guess @MonkeyDo could help with CSS for the same.

I think it looks cleaner like this, to be honest.
Less clicks for the user = more chances they bother selecting multiple options candidly.

**Review by mayhem — APPROVED** [review]
Looks good to me!

**Comment by mayhem** [comment]
As per our conversation in IRC we agreed to merge this and have a follow up PR that:

- Add support for critiquebrainz datasets
- Tweaks the UI for the datasets selection
- Fix the tests that are failing from this PR

**Pull request merged**
