### PR TITLE
Remove unnecessary colon from Month strings

### PR DESCRIPTION
**Pull request by anshuman73**

### CODE REVIEW

**Comment by anshuman73** [comment]
This is a fie for this (not exactly a ticket, but nevertheless) -

https://chatlogs.metabrainz.org/brainzbot/metabrainz/2017-01-23/?msg=3800389&page=6

**Comment by anshuman73** [comment]
> Please don't update PO or POT files in the pull request.

I've only updated message.pot as I thought they are required by the transiflex platform to update the strings in PO files.

**Comment by gentlecat** [comment]
This is not something you should worry about. I'm updating these files manually.

**Comment by anshuman73** [comment]
Alright. I'll remove them.

**Pull request merged**
