### PR TITLE
Fix small bugs in translations

### PR DESCRIPTION
**Pull request by anshuman73**

### CODE REVIEW

**Comment by anshuman73** [comment]
More to come.

**Comment by anshuman73** [comment]
More fixes to come - https://chatlogs.metabrainz.org/brainzbot/metabrainz/2017-01-16/?msg=3791277&page=5

**Comment by gentlecat** [comment]
Here are all the issues that came up so far:
https://sentry.metabrainz.org/share/issue/322e333536/
https://sentry.metabrainz.org/share/issue/322e333535/
https://sentry.metabrainz.org/share/issue/322e333534/

**Comment by anshuman73** [comment]
Unable to test the Profile error locally - (https://sentry.metabrainz.org/share/issue/322e333534/) as I cannot for some reason "sign up with musicbrainz" on local host. Tried switching to a branch which did not have my translation changes (head was at https://github.com/metabrainz/metabrainz.org/commit/adc4fcbd50c7309082fe971613a43c4632169d15) , but still the button "Sign up with MusicBrainz" gives this error - https://dpaste.de/qJ77/raw

**Comment by gentlecat** [comment]
I already pushed a change (47d3b26de4b997c5832d08650f55d0259dd48a74) which fixes those.

**Pull request closed without merging**
